global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "api_gestao-vagas"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: "api-gestao-vagas"